### ISSUE TITLE
Add contributing.md

### ISSUE THREAD

**Issue by ooade** [ooade/awesome-preact#12]
I think this is the only thing keeping us from adding to @sindresorhus's awesome list :smile:  

Any suggestions ??

**Comment by developit** [comment]
I wonder if there's an existing one we can adapt?

**Comment by ooade** [comment]
@podo's [CONTRIBUTING.md](https://github.com/podo/awesome-framer/blob/master/CONTRIBUTING.md) looks good to me... U?

**Comment by sindresorhus** [comment]
Most of the contributing.md's are adapted from https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md or https://github.com/sindresorhus/awesome/blob/master/contributing.md, the above included.

**Comment by ooade** [comment]
@sindresorhus Thanks a lot :smile_cat:
