### ISSUE TITLE
Add react-app-rewired / react-app-rewire-preact

### ISSUE THREAD

**Issue by timarney** [ooade/awesome-preact#2]
Not sure what category this would fall under as it's not a boilerplate

It's a tool to allow running Preact via Create React App without ejecting i.e. try Preact out but keep CRA.

The main repo is here https://github.com/timarney/react-app-rewired

Preact Setup is here

https://github.com/timarney/react-app-rewired/tree/master/packages/react-app-rewire-preact

**Comment by developit** [comment]
Definitely worth adding. Maybe there needs to be a section for tooling?

**Comment by timarney** [comment]
NWB calls itself a toolkit so maybe a toolkit section would work for these types of things.

**Comment by ooade** [comment]
@developit Yeah, it should be added. What category comes to your mind? :smile:

**Comment by ooade** [comment]
@timarney toolkit seem nice :+1:

**Comment by ooade** [comment]
What do you think about toolkits section @developit ?

**Comment by developit** [comment]
Yup, works for me.

**Comment by ooade** [comment]
@timarney will you like to make the PR? It'd be under Preact tools, section name: `Toolkits`

**Comment by timarney** [comment]
@ooade done - https://github.com/ooade/awesome-preact/pull/4

Stepping out for a bit.  Can fix up later as need be.

**Comment by ooade** [comment]
Thanks
